script:
  - echo $PWD
  - asdf plugin-add perla $PWD
  - asdf install perla foo
  - ln -s /usr/bin/perl asdf/installs/perla/foo/bin/perla
  - asdf reshim perla
  - asdf local perla foo
  - perla -v
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
