script: asdf plugin-test foo https://github.com/vic/asdf-link.git "ls"
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
  - ls -l /usr/local/bin /usr/bin /bin
os:
  - linux
  - osx
